// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0SxKYjA6LINqFuXR6J_nIBvDmGyuIYDc',
    appId: '1:839569705041:web:7da553fb19680d63081070',
    messagingSenderId: '839569705041',
    projectId: 'cadastro-de-alunos-b7e97',
    authDomain: 'cadastro-de-alunos-b7e97.firebaseapp.com',
    storageBucket: 'cadastro-de-alunos-b7e97.firebasestorage.app',
    measurementId: 'G-YMV5D2T64H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJJ1X8n6gCx6-c0J-R0-d5mMSdQk-ZC4',
    appId: '1:839569705041:android:356848bb0b215289081070',
    messagingSenderId: '839569705041',
    projectId: 'cadastro-de-alunos-b7e97',
    storageBucket: 'cadastro-de-alunos-b7e97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEeLe54n50tUZqKJqavbL7IBJJFhTn8U',
    appId: '1:839569705041:ios:8cf3e1b81755b5dd081070',
    messagingSenderId: '839569705041',
    projectId: 'cadastro-de-alunos-b7e97',
    storageBucket: 'cadastro-de-alunos-b7e97.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEeLe54n50tUZqKJqavbL7IBJJFhTn8U',
    appId: '1:839569705041:ios:8cf3e1b81755b5dd081070',
    messagingSenderId: '839569705041',
    projectId: 'cadastro-de-alunos-b7e97',
    storageBucket: 'cadastro-de-alunos-b7e97.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0SxKYjA6LINqFuXR6J_nIBvDmGyuIYDc',
    appId: '1:839569705041:web:d8da8c349cc97ef5081070',
    messagingSenderId: '839569705041',
    projectId: 'cadastro-de-alunos-b7e97',
    authDomain: 'cadastro-de-alunos-b7e97.firebaseapp.com',
    storageBucket: 'cadastro-de-alunos-b7e97.firebasestorage.app',
    measurementId: 'G-0E62VH0CYH',
  );
}
